spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=alexmedina
spring.datasource.password=110397
jwt.secret=this-is-a-very-safe-password-for-my-local-environment-which-needs-at-least-32-characters